version: '3'

services:

  web:
    container_name: web
    image: web
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      DEVELOPER_SERVICE: 'http://51.210.255.156:3000'